<?php

return [
    'site' => [
        'name' => 'EliasWorks',
        'description' => 'Portfolio de desarrollo de software de Luis A. Hernández Elias: backend, APIs, modernización legacy y aplicaciones transaccionales con evidencia técnica verificable.',
    ],

    'contact' => [
        'email' => 'luisitohe@gmail.com',
        'whatsapp_display' => '+598 97 092 037',
        'whatsapp_e164' => '59897092037',
        'whatsapp_url' => 'https://wa.me/59897092037?text=Hola%20Luis%2C%20te%20contacto%20desde%20EliasWorks.',
    ],

    'case_studies' => [
        [
            'name' => 'Insurance Claims Legacy Modernization',
            'eyebrow' => 'R3 full-product release · v0.3.0',
            'summary' => 'Modernización integral de gestión de siniestros con backend NestJS, frontend React, PostgreSQL y contratos API gobernados.',
            'stack' => ['TypeScript', 'NestJS 12', 'React 19', 'PostgreSQL 18', 'OpenAPI 3.1'],
            'evidence' => [
                '90 operaciones REST sobre 76 paths y 16 familias, con reconciliación runtime 90/90.',
                '22 superficies web productizadas entre journeys públicos, operación, clientes, pólizas, finanzas, administración y recuperación.',
                'OpenAPI y Postman sin drift, QA provider-real sobre PostgreSQL 18 y journeys responsive.',
                'JWT + RBAC, Argon2id, idempotencia, concurrencia, RFC 9457, auditoría durable y release gobernada v0.3.0.',
            ],
            'repository_url' => 'https://github.com/LuisHdezE/InsuranceClaims',
            'site_url' => null,
            'image' => '/images/projects/insuranceclaims.webp',
            'image_alt' => 'Vista aprobada del workspace Kanban de InsuranceClaims R3',
            'image_label' => 'Referencia UI R3 aprobada',
            'accent' => 'blue',
        ],
        [
            'name' => 'DulceHogar',
            'eyebrow' => 'E-commerce & business management',
            'summary' => 'Plataforma integral para una tienda de repostería con catálogo web, checkout y gestión operativa, ya desplegada y funcional.',
            'stack' => ['Laravel 12', 'Livewire 3', 'PostgreSQL', 'Filament 3', 'Tailwind CSS'],
            'evidence' => [
                'Catálogo, detalle de producto y checkout interactivo con Livewire.',
                'Backoffice con Filament para productos, inventario, clientes, ventas y gastos.',
                'Facturación PDF, reportes y módulos operativos integrados en una base Laravel modular.',
                'Flujos de aceptación automatizados y sitio público disponible en hosting propio.',
            ],
            'repository_url' => null,
            'site_url' => 'https://dulcehogar.eliasworks.uy/',
            'image' => '/images/projects/dulcehogar.webp',
            'image_alt' => 'Página principal de DulceHogar desplegada en dulcehogar.eliasworks.uy',
            'image_label' => 'Sitio desplegado',
            'accent' => 'rose',
        ],
        [
            'name' => 'eFactura',
            'eyebrow' => 'Brownfield .NET modernization',
            'summary' => 'Evolución brownfield de una plataforma de facturación electrónica y ventas transaccionales para Uruguay hacia una arquitectura más explícita y verificable.',
            'stack' => ['C#', '.NET 10', 'ASP.NET Core', 'EF Core', 'PostgreSQL · MySQL'],
            'evidence' => [
                'Separación progresiva en Domain, Application, Infrastructure y Web API.',
                'Persistencia provider-neutral validada sobre PostgreSQL 16 y MySQL 8.4.',
                'Fundaciones transaccionales para Sales, Catalog, Inventory, CAE, Finance y cálculo fiscal.',
                'Idempotencia, auditoría, outbox, concurrencia y rollback transaccional.',
            ],
            'repository_url' => 'https://github.com/LuisHdezE/efactura',
            'site_url' => null,
            'image' => null,
            'image_alt' => null,
            'image_label' => 'Backend transaccional',
            'accent' => 'teal',
        ],
        [
            'name' => 'ZoFloridane',
            'eyebrow' => 'Commerce experience modernization',
            'summary' => 'Modernización de una tienda WordPress/WooCommerce enfocada en experiencia móvil, claridad de compra y evolución segura sobre una plataforma existente.',
            'stack' => ['PHP', 'WordPress', 'WooCommerce', 'JavaScript', 'UI/UX'],
            'evidence' => [
                'Rediseño mobile-first de la experiencia de compra.',
                'Trabajo sobre arquitectura existente sin exponer datos productivos ni credenciales.',
                'Mejoras de carrito, localidad, entrega y flujo de pago orientado a Zelle.',
                'Entrega versionada con validación local antes de despliegue.',
            ],
            'repository_url' => 'https://github.com/LuisHdezE/ZoFloridane',
            'site_url' => 'https://zofloridane.com/',
            'image' => '/images/projects/zofloridane.webp',
            'image_alt' => 'Página principal de ZoFloridane con experiencia de compra y selección de localidad',
            'image_label' => 'Sitio desplegado',
            'accent' => 'violet',
        ],
    ],
];
